# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/college/git-repos/ascii-video-filter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/college/git-repos/ascii-video-filter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/college/git-repos/ascii-video-filter/CMakeFiles /mnt/college/git-repos/ascii-video-filter//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/college/git-repos/ascii-video-filter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AsciiVideoFilter

# Build rule for target.
AsciiVideoFilter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AsciiVideoFilter
.PHONY : AsciiVideoFilter

# fast build rule for target.
AsciiVideoFilter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsciiVideoFilter.dir/build.make CMakeFiles/AsciiVideoFilter.dir/build
.PHONY : AsciiVideoFilter/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsciiVideoFilter.dir/build.make CMakeFiles/AsciiVideoFilter.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsciiVideoFilter.dir/build.make CMakeFiles/AsciiVideoFilter.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsciiVideoFilter.dir/build.make CMakeFiles/AsciiVideoFilter.dir/main.cpp.s
.PHONY : main.cpp.s

src/Application.o: src/Application.cpp.o
.PHONY : src/Application.o

# target to build an object file
src/Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsciiVideoFilter.dir/build.make CMakeFiles/AsciiVideoFilter.dir/src/Application.cpp.o
.PHONY : src/Application.cpp.o

src/Application.i: src/Application.cpp.i
.PHONY : src/Application.i

# target to preprocess a source file
src/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsciiVideoFilter.dir/build.make CMakeFiles/AsciiVideoFilter.dir/src/Application.cpp.i
.PHONY : src/Application.cpp.i

src/Application.s: src/Application.cpp.s
.PHONY : src/Application.s

# target to generate assembly for a file
src/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsciiVideoFilter.dir/build.make CMakeFiles/AsciiVideoFilter.dir/src/Application.cpp.s
.PHONY : src/Application.cpp.s

src/AsciiConverter.o: src/AsciiConverter.cpp.o
.PHONY : src/AsciiConverter.o

# target to build an object file
src/AsciiConverter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsciiVideoFilter.dir/build.make CMakeFiles/AsciiVideoFilter.dir/src/AsciiConverter.cpp.o
.PHONY : src/AsciiConverter.cpp.o

src/AsciiConverter.i: src/AsciiConverter.cpp.i
.PHONY : src/AsciiConverter.i

# target to preprocess a source file
src/AsciiConverter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsciiVideoFilter.dir/build.make CMakeFiles/AsciiVideoFilter.dir/src/AsciiConverter.cpp.i
.PHONY : src/AsciiConverter.cpp.i

src/AsciiConverter.s: src/AsciiConverter.cpp.s
.PHONY : src/AsciiConverter.s

# target to generate assembly for a file
src/AsciiConverter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsciiVideoFilter.dir/build.make CMakeFiles/AsciiVideoFilter.dir/src/AsciiConverter.cpp.s
.PHONY : src/AsciiConverter.cpp.s

src/AsciiRenderer.o: src/AsciiRenderer.cpp.o
.PHONY : src/AsciiRenderer.o

# target to build an object file
src/AsciiRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsciiVideoFilter.dir/build.make CMakeFiles/AsciiVideoFilter.dir/src/AsciiRenderer.cpp.o
.PHONY : src/AsciiRenderer.cpp.o

src/AsciiRenderer.i: src/AsciiRenderer.cpp.i
.PHONY : src/AsciiRenderer.i

# target to preprocess a source file
src/AsciiRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsciiVideoFilter.dir/build.make CMakeFiles/AsciiVideoFilter.dir/src/AsciiRenderer.cpp.i
.PHONY : src/AsciiRenderer.cpp.i

src/AsciiRenderer.s: src/AsciiRenderer.cpp.s
.PHONY : src/AsciiRenderer.s

# target to generate assembly for a file
src/AsciiRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsciiVideoFilter.dir/build.make CMakeFiles/AsciiVideoFilter.dir/src/AsciiRenderer.cpp.s
.PHONY : src/AsciiRenderer.cpp.s

src/Utils.o: src/Utils.cpp.o
.PHONY : src/Utils.o

# target to build an object file
src/Utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsciiVideoFilter.dir/build.make CMakeFiles/AsciiVideoFilter.dir/src/Utils.cpp.o
.PHONY : src/Utils.cpp.o

src/Utils.i: src/Utils.cpp.i
.PHONY : src/Utils.i

# target to preprocess a source file
src/Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsciiVideoFilter.dir/build.make CMakeFiles/AsciiVideoFilter.dir/src/Utils.cpp.i
.PHONY : src/Utils.cpp.i

src/Utils.s: src/Utils.cpp.s
.PHONY : src/Utils.s

# target to generate assembly for a file
src/Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsciiVideoFilter.dir/build.make CMakeFiles/AsciiVideoFilter.dir/src/Utils.cpp.s
.PHONY : src/Utils.cpp.s

src/VideoDecoder.o: src/VideoDecoder.cpp.o
.PHONY : src/VideoDecoder.o

# target to build an object file
src/VideoDecoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsciiVideoFilter.dir/build.make CMakeFiles/AsciiVideoFilter.dir/src/VideoDecoder.cpp.o
.PHONY : src/VideoDecoder.cpp.o

src/VideoDecoder.i: src/VideoDecoder.cpp.i
.PHONY : src/VideoDecoder.i

# target to preprocess a source file
src/VideoDecoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsciiVideoFilter.dir/build.make CMakeFiles/AsciiVideoFilter.dir/src/VideoDecoder.cpp.i
.PHONY : src/VideoDecoder.cpp.i

src/VideoDecoder.s: src/VideoDecoder.cpp.s
.PHONY : src/VideoDecoder.s

# target to generate assembly for a file
src/VideoDecoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsciiVideoFilter.dir/build.make CMakeFiles/AsciiVideoFilter.dir/src/VideoDecoder.cpp.s
.PHONY : src/VideoDecoder.cpp.s

src/VideoEncoder.o: src/VideoEncoder.cpp.o
.PHONY : src/VideoEncoder.o

# target to build an object file
src/VideoEncoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsciiVideoFilter.dir/build.make CMakeFiles/AsciiVideoFilter.dir/src/VideoEncoder.cpp.o
.PHONY : src/VideoEncoder.cpp.o

src/VideoEncoder.i: src/VideoEncoder.cpp.i
.PHONY : src/VideoEncoder.i

# target to preprocess a source file
src/VideoEncoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsciiVideoFilter.dir/build.make CMakeFiles/AsciiVideoFilter.dir/src/VideoEncoder.cpp.i
.PHONY : src/VideoEncoder.cpp.i

src/VideoEncoder.s: src/VideoEncoder.cpp.s
.PHONY : src/VideoEncoder.s

# target to generate assembly for a file
src/VideoEncoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsciiVideoFilter.dir/build.make CMakeFiles/AsciiVideoFilter.dir/src/VideoEncoder.cpp.s
.PHONY : src/VideoEncoder.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AsciiVideoFilter"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Application.o"
	@echo "... src/Application.i"
	@echo "... src/Application.s"
	@echo "... src/AsciiConverter.o"
	@echo "... src/AsciiConverter.i"
	@echo "... src/AsciiConverter.s"
	@echo "... src/AsciiRenderer.o"
	@echo "... src/AsciiRenderer.i"
	@echo "... src/AsciiRenderer.s"
	@echo "... src/Utils.o"
	@echo "... src/Utils.i"
	@echo "... src/Utils.s"
	@echo "... src/VideoDecoder.o"
	@echo "... src/VideoDecoder.i"
	@echo "... src/VideoDecoder.s"
	@echo "... src/VideoEncoder.o"
	@echo "... src/VideoEncoder.i"
	@echo "... src/VideoEncoder.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

